### ISSUE TITLE
create Clone

### ISSUE THREAD

**Issue by amirwolf5122** [KoRrNiK/BaseBuilder-TURBO#2]
Hi
How can I add the clone feature to base builder 6.5?
### 
	new ent=create_entity("func_wall");
	if( !pev_valid(ent) ) return -1;
	
	new szClassName[16];
	pev(entView, pev_classname, szClassName, sizeof(szClassName));
	set_pev(ent,pev_classname, szClassName);
	
	pev(entView, pev_model, szClassName, sizeof(szClassName));
	set_pev(ent,pev_model, szClassName);
	
	set_pev(ent,pev_solid, pev(entView, pev_solid));
	set_pev(ent,pev_movetype, pev(entView, pev_movetype));
	set_pev(ent,pev_modelindex, pev(entView, pev_modelindex));
	set_pev(ent,pev_body, pev(entView, pev_body));
	set_pev(ent,pev_skin, pev(entView, pev_skin));
	set_pev(ent,pev_flags, pev(entView, pev_flags));
	set_pev(ent,pev_spawnflags, pev(entView, pev_spawnflags));
	set_pev(ent,pev_team, pev(entView, pev_team));
	
	new Float:fFloat[3];
	pev(entView, pev_mins, fFloat);
	set_pev(ent, pev_mins, fFloat);
	
	pev(entView, pev_maxs, fFloat);
	set_pev(ent, pev_maxs, fFloat);	
	
	pev(entView, pev_vuser3, fFloat);
	set_pev(ent, pev_vuser3, fFloat);
	
	pev(entView, pev_vuser1, fFloat);
	set_pev(ent, pev_vuser1, fFloat);
	
	setOwner(ent, getOwner(entView));
	pev(entView, pev_origin, fFloat);
	entity_set_origin(ent, fFloat);
	setLock(ent, 3);

	return ent;
if I'm not mistaken

**Comment by kacorvixon1337** [comment]
copy clcmd and public + set the owner of ent
