### ISSUE TITLE
Donate points

### ISSUE THREAD

**Issue by 1ZzZzZ1** [KoRrNiK/BaseBuilder-TURBO#3]
Hi
Please provide a list of available commands with descriptions
How to give xp or level to others?
Is there an order?
Can you add a pet?

**Comment by KoRrNiK** [comment]
### Hello :) 

Most of the commands and messages in the plugin are in Polish, so it would have to be changed (or I will add language support in the future)

> _Most of the commands have a shortening function, so just type a few symbols_
#### All commands: 
* /konto, /haslo, /zaloguj, /login - `Account `
* /sklep, /shop - `Shop`
* /odblokuj, /o - `Unstuck`
* /czas, /time - `Play Time`
* /team, /dru, /zap, /t - `Team`
* /guns, /weap, /bron - `Weapon Menu`
* /happy - `Chcek happy time`
* /me - `Global Menu`
* /klasa - `Class Zombie or Human`
* /zombi - `Class Zombie`
* /budowniczy - `Class Human`
* /help, /pomoc, /p - `Request for help`
* /misj, /sekretna, /podstawowa - `Mission`
* /sms - `Sms shop`
* /vip, /svip - `Vip Menu`
* /kopalnia - `Cave`
* /top - `Top & rank`
* /rank - `Rank`
* /info nick - `Info player`
* /maxdmg - `Your MaxDMG`
* /resetdmg - `Reset MaxDMG`
* /id - `Your ID #xxxx
* /nagroda - `Award `
* /k, /kolor, /color - `Color menu block VIP`
* /komendy - `Commands`
* /regulamin - `Regulations`
* /admins - `Online Admins`
* /klan - `Clan`
* /free - `Free Award`
* /hide - `Turn off the visibility of people on your team`
* /exp - `Show your EXP Class & Weapon`
* /daj nick value - `Sent Nuggets`
* /kostium - `Costumes`
* /zabij - `How much do you pay for the murder`
* /wycisz - `Mute Player`
* /miesiac - `Award every month (I don't know why I did it)`
* /rozlaczeni - `Disconnected Players`
* /w #id text - `Private message to Player`

#### Admin commands:
* /swiatlo - `Light menu`
* /clone - `Clone block settings`
* /runhappy - `Happy admin menu`
* /hp nick value - `Give hp`
* /tp nick - `Teleport to player`
* /tome nick/#all/#ct/#tt - `Teleport player/s to me`
* /warn, /ostrzez - `Warning menu`
* /a, /admin - `Admin menu` 
* /release - `Release the zombies ahead of time`
* /revive nick - `Revive player`
* /swap nick - `Swap player`
* /mute - `Mute player - all players`
* > console command: clearData - `Clear Database ( sql / fvault / sql + fvault )`

#### To add a currency to someone, you need the "a" flag and the menu is in `/sms` > `6.`
#### I had plans to add pet once, but I didn't, and I don't know if I will.

**Comment by 1ZzZzZ1** [comment]
Hi
Its translation capability needs to be added. I hope you can work on it
Why not add a pet?
I have already seen this feature in this mode

**Comment by KoRrNiK** [comment]
In older versions I tried to do it, but I didn't finish it, I have the code somewhere and I could finish it someday.
Same as with the translation I started to do once and didn't finish.
Everything I did for the store can be found in the plugin here.

**Comment by 1ZzZzZ1** [comment]
Thank you very much
And I have another suggestion
I looked at your code and added an item to it, I hope you look at it
If the CountDown reaches 30, the color of the hud will change to yellow, and if it reaches 10 seconds, it will change to red.
[roundSystem.zip](https://github.com/KoRrNiK/BaseBuilder-TURBO/files/7596893/roundSystem.zip)

**Comment by KoRrNiK** [comment]
We will think :)
