### ISSUE TITLE
 Problem cmdSay

### ISSUE THREAD

**Issue by milad512** [KoRrNiK/BaseBuilder-TURBO#5]
Hello
This base builder mode prevents other plugins from executing chat commands

**Comment by amirwolf513** [comment]
solved

		chatPrint(id, PREFIX_LINE, "Nie ma takiej komendy");
		return PLUGIN_HANDLED;
--->
		//chatPrint(id, PREFIX_LINE, "Nie ma takiej komendy");
		return PLUGIN_CONTINUE;
